### ISSUE TITLE
FileChooser.choose not perform any action.

### ISSUE THREAD

**Issue by Amitpalsd** [myflashlab/fileChooser-ANE#16] opened 2017-04-15 15:50 UTC
Hello! 

I seen demo FD application and used same code in my project to access image from mobile device.

But fileChoose.choose ("image/*", "pick image") perform no action.

Please help.

regards/Amitpal

**Comment by Amitpalsd** [comment] 2017-04-16 23:37
I see filechooser properties like "os" working but it is not accessing images.

**Comment by myflashlab** [comment] 2017-04-20 05:23
Are you sure you have set your manfiest .xml file correctly? https://github.com/myflashlab/fileChooser-ANE#air-xml-manifest

**Comment by jonathanhollander** [comment] 2017-05-11 19:58
I am having the same problem. I'm only testing on Android, AIR 25, Android 6.0.1, on Galaxy S5.  I've double checked all the manifest.xml and it's there...  it's only 2 lines to add for Android, so not hard to mess up. When I run the "._ex.choose("*/*", "pick a file!");" nothing happens.

**Comment by jonathanhollander** [comment] 2017-05-15 15:46
sucks to purchase an ANE (The image picker)... find out you actually need to purchase another ANE (Permission request)... to then find an issue where it doesn't work, make a post asking for help, then not get a response in 4 days.... cricket cricket

**Comment by Amitpalsd** [comment] 2017-05-15 15:54
Hi Jonathan, pls do let me know if you make it work somehow. ane is not
working for me.

**Comment by myflashlab** [comment] 2017-05-19 14:42
@jonathanhollander The permission ANE was born shortly after AIR SDK 24 when Adobe used the latest Android tools which was forcing manual permissions. Google forced it, Adobe was forced to update itself and eventually we had to find a solution. 

Anyway, guys, just saying that something does not work, is not very helpful! Give us more information.

**Comment by jonathanhollander** [comment] 2017-05-19 14:54
@myflashlab I understand that and that's not the issue. The issue is that no where on this page: http://www.myflashlabs.com/product/file-image-pick-ane-adobe-air-native-extension/ did it say "BTW, you also have to buy another ANE if you want this to work correctly". Only after you purchase and start using it do you find out.

Besides what I've already mentioned I'm not sure what more you want me to provide. I'm testing on Android, AIR 25, Android 6.0.1, on a Galaxy S5, I've verified I have the android manifest correctly as it's only 2 lines.  I run the only method you can run "_ex.choose" and nothing happens, no errors, just nothing happens. I've incorporated the RequestPermission ANE correctly, as I see it ask for permission and verify it's granted... but again when I run the only method you can run "_.ex.choose", nothing happens. I'm sorry if you want more but I have no idea what else I can tell you, it just doesn't work.

BTW 8 days response time kinda sucks... on your website it says "Our Android, iOS and AS team leaders are constantly checking on our GitHub issues pages trying to answer your tech questions as fast as they can. " hopefully I hear back before the 27th.

**Comment by jonathanhollander** [comment] 2017-06-01 15:23
ANYBODY HOME?!?!

**Comment by jonathanhollander** [comment] 2017-06-06 16:08
I am now speaking to the Void where these comments appear to go... Void, if you happen to see MyFlashLabs can you tell them that their user base is looking for them... Thank you Void

**Comment by myflashlab** [comment] 2017-06-07 06:31
1) Are you using the demo ANE? or the licensed one? If you are using the demo ANE and you are seeing the "demo dialog" thing, make sure you are not calling ```_ex.choose("*/*", "pick a file!");``` prior to closing the dialog box.

2) On Android, you need the permissionCheck ANE. Are you sure you have set that ANE correctly? Please try to post your manifest here so we can check it out also.

Guys, what's up with the angry voice! We do have the responsibility to support you but give us something to play with! You're not sending your manifest, you're not sending any error logs, and you expect us to guess? Anyway, let's concentrate on the issue from now on. But you can always trust us when we are honestly saying that we are on YOUR side! we want you to be able to use our ANEs. We are doing our best to improve everything. We are on YOUR SIDE :) Thanks.

**Comment by jonathanhollander** [comment] 2017-06-07 15:12
Are you SERIOUS? "Whats up with the angry voice!"? Yes i'm angry, I DESERVE TO BE ANGRY. THE ISSUE IS THE RESPONSE TIME, you can't seriously come back here and comment 19 days later and pretend to NOT know the issue is response time. The angry voice is a result of me being able to talk to the VOID. How can you not see this? How about replying with those 2 points 19 days ago? maybe before I've already gone and asked for a refund chargeback from paypal...because I assumed you guys have dropped off the face of the planet. It took less time to build my entire app than to get a response from you. You've got to admit, it's oddly suspicious you guys FINALLY RESPOND the day after I do the paypal charge back... 

I reached out here.
I reached out by private messaging you on the Starling Forum.
I reached out by filling out your Contact form here: http://www.myflashlabs.com/contact/
I reached out by reviving a Starling Forum thread that you guys even responded twice but still managed to ignore my problem. 

And as to your 2 suggested points... have you read ANYTHING above your own post? The part where I complained that after I BOUGHT the production ANE... to then later realize I have to buy the RequestPermission ANE.  So YES, I'm not using the demo, and YES I'm using the require permissions ANE. And again had you read the above, you would also notice I mentioned in 2 separate comments that the  Android manifest was only 2 lines.... so almost impossible to mess up but sure I'll copy and paste it here:
<uses-sdk android:targetSdkVersion="23"/>
<activity android:name="com.doitflash.fileBrowser.Chooser" android:theme="@style/Theme.Transparent" />

Yeah MAYBE you are on OUR SIDE... or MAYBE you charge people money and don't respond when they need help or when you do respond, it's 19 days later and you respond oblivious to your customers feelings and pretend THEY are at fault for not providing you the information you needed to fix the issue. Of course we don't expect you to guess... we expect you to just respond with helpful information in a  timely manner. And what do you mean logs? You make too many assumptions about what people are suppose to give you without telling them what it is.

Hell YES I am angry !!!!

**Comment by myflashlab** [comment] 2017-06-08 09:14
We are so sorry to be seeing you up to this level of being angry. We are trying to work with you by concentrating on the tech side but you are keeping on focusing on the side facts. I'm not going to explain these again but here they are, for the last time. Please try to read our post as a friendly reminder.

1. We have explained that Club members will have our fast support and other buyers will have Github repositories to ask their tech questions. However, we always do our best to reply all questions as fast as possible.
2. "Yes i'm angry, I DESERVE TO BE ANGRY." Everyone has the right to be angry from time to time! But that does not make much sense. Why? Because demo versions of our ANEs are available for download for free.
3. "have you read ANYTHING above your own post?" We have. But have you?! You are using the permission check ANE too in your project, then your project manifest must have other entities in it also. What you posted shows that you have not setup the permission check ANE!
4. "...You make too many assumptions about what people are suppose to give you without telling them what it is..." I don't think so. You are a developer and you should know that leaving a comment like ```When I run the "._ex.choose("/", "pick a file!");" nothing happens.``` is not going to help you solve anything!
5. "...oddly suspicious you guys FINALLY RESPOND the day after I do the paypal charge back..." You are misjudging the whole thing pal. Please refer to the my previous notes.

To get faster responses, consider joining the club or consider buying our live support on Skype/teamviewer. 

So, Are we going to talk about the tech side now?!

**Comment by quantuan** [comment] 2017-08-11 08:51
hi admin
I also have this problem with Android 7.0, on a Sony XA Ultral. Although i do flow guide
how to fix it?
Thank you.

**Comment by myflashlab** [comment] 2018-12-14 14:22
**NOTICE:** If you need MyFlashLabs developers' professional help, you should be either a [club member](https://www.myflashlabs.com/product/myflashlabs-club-membership/) or have a [premium support package](https://www.myflashlabs.com/product/myflashlabs-support/).

**Closed by myflashlab** 2018-12-14 14:22 UTC
